### ISSUE TITLE
Feature: Upgrade to latest version of the pizza-cli

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/pizza-action#4]
Currently we're using the beta branch. See https://github.com/open-sauced/pizza-action/blob/main/action.yml#L29C1-L32C18. 

We should update to what we consider the latest stable release as some bug fixes/features are in flight at the moment.

**Comment by nickytonline** [comment]
@jpmcb, in action.yml, do you think it's reasonable to always have the latest version of the CLI set?

Currently it's `@beta`, but I was going to hard-code a specific release for the launch, see https://github.com/open-sauced/pizza-action/blob/main/action.yml#L35, but I'm thinking `@latest` seems fine.

The pizza-action is pretty much feature complete so just wondering if it makes sense to release everytime we have a CLI release.

Another option is we could default to `@latest`, but we could add another input to the action which could be `cli-version` which would default to `latest`. Something like this.

```diff
name: "OpenSauced Pizza Action"
description: "GitHub Action to run OpenSauced's Pizza CLI's various commands"
branding:
  icon: "package"
  color: "orange"
inputs:
  pizza-args:
    description: "OpenSauced Pizza CLI command to run"
    default: "generate codeowners ./ --tty-disable"
    required: true
  commit-and-pr:
    description: "Commit and push changes"
    default: "false"
    required: false
  pr-title:
    description: "Custom pull request title"
    default: "chore (automated): OpenSauced updates"
    required: false
+  cli-version:
+    description: "The pizza CLI version to use"
+    default: "latest"
+    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22.5"

    - name: Install pizza CLI
      run: |
-        go install github.com/open-sauced/pizza-cli@beta
+        go install github.com/open-sauced/pizza-cli@${{ inputs.cli-version }}
      shell: bash

    - name: Check pizza CLI version
      run: pizza-cli version
      shell: bash

    - name: Run pizza CLI command
      run: |
        pwd
        ls -la
        pizza-cli ${{ inputs.pizza-args }}
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Make script executable
      run: chmod +x ${{ github.action_path }}/scripts/create-pr.sh
      shell: bash

    - name: Setup git config
      run: |
        git config user.name 'open-sauced[bot]'
        git config user.email '63161813+open-sauced[bot]@users.noreply.github.com'
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Create a PR with pizza CLI changes
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ inputs.commit-and-pr == 'true' }}
      run: |
        export CUSTOM_PR_TITLE="${{ inputs.pr-title }}"
        ${{ github.action_path }}/scripts/create-pr.sh
      shell: bash
      working-directory: ${{ github.workspace }}
```

**Comment by jpmcb** [comment]
> Another option is we could default to `@latest`, but we could add another input to the action which could be cli-version which would default to latest. Something like this.

^ This is the way. Technically the `pizza-action` and `pizza-cli` are completely seperate pieces of software and should not couple their version mechanics.

If we were going to just take `latest`, people would enevitably consume breaking changes. For example, say there's a breaking change in v1.2.3 of the pizza-cli and people continue to consume v7.8.9 of the pizza-action (and thus consume the `latest` which would bring in v1.2.3).

Decoupling the version of the configuration software with the version of the dependent software will be a net win.

So, yes, I'd say a  `cli-version` config makes alot of sense and default to `latest` is 👍🏼 

---

Note: this is very similar to how other `setup` actions work: https://github.com/actions/setup-go
